name: GitHub Actions Demo
run-name: ${{ github.actor }} is running application build 🚀
on: [push]

env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "590810503117"

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCES_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: 'false'
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ env.AWS_ACCOUNT_ID }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # DOCKER_BUILDKIT=1 docker buildx build --progress=plain --tag test -f ./app/Dockerfile .
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          #build-args: ${{ inputs.build-args }}
          #secrets: ${{ inputs.secrets }}
          #secret-files: ${{ inputs.secret-files }}
          push: false
          file: ./app/Dockerfile
          tags: devexhiringtest-cmardonesp
          #cache-from: type=gha
          #cache-to: type=gha,mode=max
          context: .
          #target: ${{ inputs.target }}
          #platforms: ${{ inputs.platforms }}
          #load: ${{ inputs.load }}